---
stages:
- name: BUILD
  properties:
  - name: SERVICE_NAME
    value: ${SERVICE_NAME}
    type: text
  - name: CLUSTER_NAMESPACE
    value: ${CLUSTER_NAMESPACE}
    type: text
  - name: ACCESS_ENDPOINT_NAME
    value: ${ACCESS_ENDPOINT_NAME}
    type: text
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}    
  triggers:
  - type: commit
  jobs:
  - name: Container build
    type: builder
    build_type: cr
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      set -x
     
      mkdir -p $ARCHIVE_DIR
      echo -e "Build environment variables:" > $ARCHIVE_DIR/build.properties
      echo "CLUSTER_NAMESPACE=${CLUSTER_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
      echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
      echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
      echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
      echo "SERVICE_NAME=${SERVICE_NAME}" >> $ARCHIVE_DIR/build.properties
      echo "CF_APP_NAME=${CF_APP_NAME}" >> $ARCHIVE_DIR/build.properties
      echo "ACCESS_ENDPOINT_NAME=${ACCESS_ENDPOINT_NAME}" >> $ARCHIVE_DIR/build.properties
      # Learn more about the available environment variables at:
      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment

      # To review or change build options use:
      # bx cr build --help

      echo "=========================================================="
      pwd
      ls
      mv ae-register-Template.yaml ${SERVICE_NAME}.yaml
      echo "========================${SERVICE_NAME}.yaml=================================="
      cat ${SERVICE_NAME}.yaml
      
- name: VALIDATE
  inputs:
  - type: job
    stage: BUILD
    job: Container build
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file  
  jobs:
  - name: Vulnerability Advisor
    type: tester
    test_type: vulnerabilityadvisor
    use_image_from_build_input: true
    fail_stage: false
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      # uncomment to debug the script
      # set -x
      
      # Input env variables (can be received via a pipeline environment properties.file.
      echo "IMAGE_NAME=${IMAGE_NAME}"
      echo "BUILD_NUMBER=${BUILD_NUMBER}"
      echo "REGISTRY_URL=${REGISTRY_URL}"
      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
      #View build properties
      
      echo "TODO: check availability of access endpoint!"

- name: REGISTER
  inputs:
  - type: job
    stage: BUILD
    job: Container build
  properties:
  - name: buildprops
    value: build.properties
    type: file  
  jobs:
  - name: Register Service Access Endpoint
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      # uncomment to debug the script
      #set -x
      # copy the script below into your app code repo (e.g. ./scripts/deploy_kubectl.sh) and 'source' it from your pipeline job
      #    source ./scripts/deploy_kubectl.sh
      # alternatively, you can source it from online script:
      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
      # ------------------
      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh
      # Input env variables (can be received via a pipeline environment properties.file.
      #echo "BUILD_NUMBER=${BUILD_NUMBER}"
      #echo "REGISTRY_URL=${REGISTRY_URL}"
      #echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
      #echo "REGISTRY_TOKEN=${REGISTRY_TOKEN}"
      #View build properties
      #cat build.properties
      # also run 'env' command to find all available env variables
      # or learn more about the available environment variables at:
      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment

      # Input env variables from pipeline job
      echo "PIPELINE_KUBERNETES_CLUSTER_NAME=${PIPELINE_KUBERNETES_CLUSTER_NAME}"
      echo "CLUSTER_NAMESPACE=${CLUSTER_NAMESPACE}"
      echo "SERVICE_NAME=${SERVICE_NAME}"
      echo "ACCESS_ENDPOINT_NAME=${ACCESS_ENDPOINT_NAME}"
      echo "=======================Registering Service=========================="
      source ops_ae_registry.sh
      